name: PR checks

on:
  pull_request:
    branches: [ main ]

jobs:
  call-workflow-maven-deploy:
    uses: felleslosninger/github-workflows/.github/workflows/ci-pr-checks-lib.yml@main
    permissions:
      contents: write
      packages: write
    with:
      java-version: 21
    secrets: inherit
