# This workflow publishes the library to GitHub Packages when a release is created
# It delegates the build/publish steps to a reusable workflow in felleslosninger/github-workflows
name: Release to GitHub Packages

on:
  release:
    types:
      - created

jobs:
  call-workflow-build-publish:
    uses: felleslosninger/github-workflows/.github/workflows/ci-build-publish-lib.yml@main
    permissions:
      contents: write
      packages: write
    with:
      java-version: 21
      package-version: ${{ github.event.release.tag_name }}
      deployment-repository: ${{ github.repository }}
    secrets: inherit
